import React from 'react'
import { Layout, Breadcrumb } from 'antd';

import SideBar from '../components/SideBar'
import NavbarFIxed from '../components/NavbarFixed2'

const Home = () => {
  const { Content, Footer } = Layout;

  return (
    <div>
      <Layout>
        {/* sidebar */}
        <SideBar />

        {/* Layout */}
        <Layout>
          {/* <Header style={{ background: '#2A4DAC', padding: 0 }} /> */}
          <NavbarFIxed />
          <Content style={{ margin: '0 16px' }}>
            <Breadcrumb style={{ margin: '16px 0' }}>
              <Breadcrumb.Item>User</Breadcrumb.Item>
              <Breadcrumb.Item>Bill</Breadcrumb.Item>
            </Breadcrumb>
            <div style={{ padding: 24, background: '#fff', textAlign: 'center' }}>
              ...
          <br />
              Really
          <br />
              ...
          <br />
              ...
          <br />
              ...
          <br />
              long
          <br />
              ...
          <br />
              ...
          <br />
              ...
          <br />
              ...
          <br />
              ...
          <br />
              ...
          <br />
              ...
          <br />
              ...
          <br />
              ...
          <br />
              ...
          <br />
              ...
          <br />
              ...
          <br />
              ...
          <br />
              ...
          <br />
              ...
          <br />
              ...
          <br />
              ...
          <br />
              ...
          <br />
              ...
          <br />
              ...
          <br />
              ...
          <br />
              ...
          <br />
              ...
          <br />
              ...
          <br />
              ...
          <br />
              ...
          <br />
              ...
          <br />
              ...
          <br />
              ...
          <br />
              ...
          <br />
              ...
          <br />
              ...
          <br />
              ...
          <br />
              ...
          <br />
              ...
          <br />
              ...
          <br />
              ...
          <br />
              ...
          <br />
              ...
          <br />
              ...
          <br />
              ...
          <br />
              content
        </div>
          </Content>
          <Footer style={{ textAlign: 'center' }}>Ant Design ©2018 Created by Ant UED</Footer>
        </Layout>
      </Layout>
    </div>
  )
}

export default Home
